"""LangGraph review pipeline.

    fetch_context -> retrieve_similar_prs -> review -> format_comment -> post_comment

Each node is a plain function decorated with `@traceable` so it shows up as
its own step in LangSmith (in addition to LangGraph's own per-node run
tracking) — see app/core/tracing.py for how that's wired up.

Nodes call the same functions the MCP server (app/mcp/server.py) exposes
(app/mcp/tools.py) directly, rather than round-tripping through an MCP stdio
subprocess on every graph run — that keeps eval-harness latency (Phase 4)
honest and avoids spawning a process per review. The MCP server itself stays
the interface for any *external* MCP client (Claude Desktop, another agent)
to reach these same tools; both paths share one implementation.
"""
from __future__ import annotations

from typing import TypedDict

from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import END, StateGraph
from langsmith import traceable

from app.agents.llm import review_with_fallback
from app.agents.prompts import (
    REVIEW_HUMAN_TEMPLATE,
    REVIEW_SYSTEM_PROMPT,
    format_coding_standards,
    format_similar_prs,
)
from app.agents.schema import ReviewResult
from app.core.github_client import GitHubClient, get_github_client
from app.core.logging import get_logger
from app.core.tracing import setup_tracing
from app.mcp import tools

log = get_logger(__name__)
setup_tracing()


class ReviewState(TypedDict, total=False):
    pr_id: str          # "owner/repo#123"
    repo: str
    number: int
    dry_run: bool        # if True, never calls the GitHub write API

    pr: dict              # get_pr_diff() output
    coding_standards: dict
    similar_prs: dict

    review: dict           # ReviewResult.model_dump()
    model_used: str

    comment_body: str
    comment_id: int | None
    skipped_post_reason: str | None


@traceable(name="fetch_context")
def fetch_context(state: ReviewState) -> ReviewState:
    pr = tools.get_pr_diff(state["pr_id"])
    standards = tools.get_repo_coding_standards(state["repo"])
    return {**state, "pr": pr, "coding_standards": standards}


@traceable(name="retrieve_similar_prs")
def retrieve_similar_prs(state: ReviewState) -> ReviewState:
    similar = tools.get_similar_prs(state["pr"]["diff"], n_results=5)
    return {**state, "similar_prs": similar}


@traceable(name="review")
def review(state: ReviewState) -> ReviewState:
    pr = state["pr"]
    messages = [
        SystemMessage(content=REVIEW_SYSTEM_PROMPT),
        HumanMessage(
            content=REVIEW_HUMAN_TEMPLATE.format(
                repo=state["repo"],
                title=pr["title"],
                author=pr["author"],
                diff=pr["diff"][:12000],
                coding_standards=format_coding_standards(state["coding_standards"]["sources"]),
                similar_prs=format_similar_prs(state["similar_prs"]["results"]),
            )
        ),
    ]
    result, model_used = review_with_fallback(messages)
    if not isinstance(result, ReviewResult):
        result = ReviewResult.model_validate(result)
    log.info(
        "review done model=%s findings=%d risk=%s",
        model_used, len(result.findings), result.overall_risk,
    )
    return {**state, "review": result.model_dump(), "model_used": model_used}


_SEVERITY_EMOJI = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}


@traceable(name="format_comment")
def format_comment(state: ReviewState) -> ReviewState:
    review_data = state["review"]
    findings = review_data["findings"]

    lines = [
        "## 🤖 PRSense Review",
        "",
        review_data["summary"],
        "",
        f"**Overall risk:** {review_data['overall_risk']}  ·  **Model:** `{state['model_used']}`",
        "",
    ]
    if not findings:
        lines.append("No issues found. ✅")
    else:
        lines.append(f"### Findings ({len(findings)})")
        lines.append("")
        for f in findings:
            emoji = _SEVERITY_EMOJI.get(f["severity"], "⚪")
            loc = f"{f['file']}" + (f":{f['line']}" if f.get("line") else "")
            lines.append(f"{emoji} **[{f['severity'].upper()} · {f['issue_type']}]** `{loc}`")
            lines.append(f"> {f['explanation']}")
            if f.get("suggestion"):
                lines.append(f"> 💡 {f['suggestion']}")
            lines.append("")
    lines.append("---")
    lines.append("_Generated by [PRSense](https://github.com/AnvayP1998/PRSense) · "
                  "an issue here? react 👎 and it'll be excluded from training data._")
    return {**state, "comment_body": "\n".join(lines)}


@traceable(name="post_comment")
def post_comment(state: ReviewState, *, client: GitHubClient | None = None) -> ReviewState:
    if state.get("dry_run", True):
        log.info("dry_run=True — not posting to %s", state["pr_id"])
        return {**state, "comment_id": None, "skipped_post_reason": "dry_run"}

    gh = client or get_github_client()
    comment_id = gh.post_pr_comment(state["repo"], state["number"], state["comment_body"])
    return {**state, "comment_id": comment_id, "skipped_post_reason": None}


def build_graph():
    g = StateGraph(ReviewState)
    g.add_node("fetch_context", fetch_context)
    g.add_node("retrieve_similar_prs", retrieve_similar_prs)
    g.add_node("review", review)
    g.add_node("format_comment", format_comment)
    g.add_node("post_comment", post_comment)

    g.set_entry_point("fetch_context")
    g.add_edge("fetch_context", "retrieve_similar_prs")
    g.add_edge("retrieve_similar_prs", "review")
    g.add_edge("review", "format_comment")
    g.add_edge("format_comment", "post_comment")
    g.add_edge("post_comment", END)
    return g.compile()


def run_review(pr_id: str, *, dry_run: bool = True) -> ReviewState:
    repo, number = tools.parse_pr_id(pr_id)
    graph = build_graph()
    initial: ReviewState = {
        "pr_id": pr_id, "repo": repo, "number": number, "dry_run": dry_run,
    }
    return graph.invoke(initial)
